version: "3"

services:
  mixcloud-play:
    image: electronuserland/builder:14-05.21
    volumes:
      - .:/project
      - ~/.cache/electron:/root/.cache/electron
      - ~/.cache/electron-builder:/root/.cache/electron-builder
    environment:
      ELECTRON_CACHE: "/root/.cache/electron"
      ELECTRON_BUILDER_CACHE: "/root/.cache/electron-builder"
    working_dir: /project
    command: /bin/bash -c "npm install && npm build:debug" # build on a macOS host for dist